- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: Devops with AWS
    DURATION: 10HR
    TRAINER: SIVA
  tasks:
    - name: print course information
      vars:
        COURSE: Ansible
      ansible.builtin.debug:
      #vars reference should be surrounded by ""
        msg: "Hello {{ COURSE }}, COURSE DURAION: {{ DURATION }}, TRAINER IS {{ TRAINER }}"

    - name: print course information
      ansible.builtin.debug:
      #vars reference should be surrounded by ""
        msg: "Hello {{ COURSE }}, COURSE DURAION: {{ DURATION }}, TRAINER IS {{ TRAINER }}"

