- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello, {{ item  }}" #item is reserved keyword
    loop:
    - suresh
    - ramesh
    - ram
    - harish